name: Carfie
attributes:
  ORGANIZATIONNAME: Carfie
options:
  bundleIdPrefix: com.carfie
  deploymentTarget:
    iOS: "11.0"
  groupSortPosition: top
  minimumXcodeGenVersion: 2.7.0

targets:
  Rider:
    scheme:
      testTargets:
        - RiderTests
    platform: iOS
    type: application
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.carfie.rider
        TARGETED_DEVICE_FAMILY: "1" #iPhone
        CODE_SIGN_ENTITLEMENTS: Rider/Rider.entitlements
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: MVJFXK77H6
        CURRENT_PROJECT_VERSION: 14
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "iPhone Developer"
          PROVISIONING_PROFILE_SPECIFIER: "Carfie Rider Dev"
        Release:
          CODE_SIGN_IDENTITY: "iPhone Distribution"
          PROVISIONING_PROFILE_SPECIFIER: "Carfie Rider Distribution"
    postBuildScripts:
      - path: fabric-run.sh
        name: Fabric Run
    sources:
      - path: Core
      - path: CreditCardForm
      - path: Rider

  Driver:
    scheme:
      testTargets:
        - DriverTests
    platform: iOS
    type: application
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.carfie.driver
        TARGETED_DEVICE_FAMILY: "1" #iPhone
        CODE_SIGN_ENTITLEMENTS: Driver/Driver.entitlements
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: MVJFXK77H6
        CURRENT_PROJECT_VERSION: 14
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "iPhone Developer"
          PROVISIONING_PROFILE_SPECIFIER: "Carfie Driver Dev"
        Release:
          CODE_SIGN_IDENTITY: "iPhone Distribution"
          PROVISIONING_PROFILE_SPECIFIER: "Carfie Driver Distribution"
    postBuildScripts:
      - path: fabric-run.sh
        name: Fabric Run
    sources:
      - path: Core
      - path: CreditCardForm
      - path: Driver

  RiderTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - path: RiderTests
    dependencies:
      - target: Rider

  DriverTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - path: DriverTests
    dependencies:
      - target: Driver

  CoreTests:
    settings:
      base:
        DEVELOPMENT_TEAM: MVJFXK77H6
    scheme:
      testTargets:
        - CoreTests
    platform: iOS
    type: bundle.unit-test
    sources:
      - path: Core
      - path: CoreTests