name: Carfie
options:
  bundleIdPrefix: com.espy
  deploymentTarget:
    iOS: "11.0"
  groupSortPosition: top
  minimumXcodeGenVersion: 2.7.0

targets:
  Rider:
    scheme:
      testTargets:
        - RiderTests
    platform: iOS
    type: application
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.espy.user
        TARGETED_DEVICE_FAMILY: "1" #iPhone
        CODE_SIGN_ENTITLEMENTS: Rider/Rider.entitlements
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: V46XQZ3Q67
        CURRENT_PROJECT_VERSION: 9
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "iPhone Developer"
          PROVISIONING_PROFILE_SPECIFIER: "Carfie Dev"
        Release:
          CODE_SIGN_IDENTITY: "iPhone Distribution"
          PROVISIONING_PROFILE_SPECIFIER: "Espy User Dist"
    postBuildScripts:
      - path: fabric-run.sh
        name: Fabric Run
    sources:
      - path: Core
      - path: CreditCardForm
      - path: Rider

  Driver:
    scheme:
      testTargets:
        - DriverTests
    platform: iOS
    type: application
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.espy.provider
        TARGETED_DEVICE_FAMILY: "1" #iPhone
        CODE_SIGN_ENTITLEMENTS: Driver/Driver.entitlements
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: V46XQZ3Q67
        CURRENT_PROJECT_VERSION: 9
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "iPhone Developer"
          PROVISIONING_PROFILE_SPECIFIER: "Carfie Driver Dev"
        Release:
          CODE_SIGN_IDENTITY: "iPhone Distribution"
          PROVISIONING_PROFILE_SPECIFIER: "Espy Provider Dist"
    postBuildScripts:
      - path: fabric-run.sh
        name: Fabric Run
    sources:
      - path: Core
      - path: CreditCardForm
      - path: Driver

  RiderTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - path: RiderTests
    dependencies:
      - target: Rider

  DriverTests:
    platform: iOS
    type: bundle.unit-test
    sources:
      - path: DriverTests
    dependencies:
      - target: Driver

  CoreTests:
    scheme:
      testTargets:
        - CoreTests
    platform: iOS
    type: bundle.unit-test
    sources:
      - path: Core
      - path: CoreTests