# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2

jobs:
  build:
  generate-project-file:
    macos:
      xcode: "11.0"
    steps:
      - checkout
      - run:
          command: |
            brew install xcodegen
            xcodegen generate

  install-cocoapods:
    macos:
      xcode: "11.0"
    steps:
      - checkout
      - run:
          name: Fetch CocoaPods specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install CocoaPods
          command: pod install

  core-tests:
    macos:
      xcode: "11.0"
    steps:
      - checkout
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: CoreTests

workflows:
  version: 2
  build-test:
    jobs:
      - generate-project-file
      - install-cocoapods
      - build
      - core-tests
