# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2

jobs:
  generate-project-file:
    macos:
      xcode: "11.0"
    steps:
      - checkout
      - run:
          command: |
            brew install xcodegen
            xcodegen generate

  install-cocoapods:
    macos:
      xcode: "11.0"
    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            pod install

  core-tests:
    macos:
      xcode: "11.0"
    steps:
      - checkout
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: CoreTests
