# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2

jobs:
  build:
    macos:
      xcode: "11.0"
    steps:
      - checkout

      # Install Xcodegen and create the project file from source
      - run:
          command: |
            HOMEBREW_NO_AUTO_UPDATE=1 brew install xcodegen
            xcodegen generate

      # Fetch Cocoapods specs from the CircleCI cache to save build time
      - run:
          name: Fetch CocoaPods specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf

      # Install Cocoapods
      - run:
          name: Install CocoaPods
          command: pod install

      # Run Core tests
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: CoreTests
