# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2

jobs:
  build:
    macos:
      xcode: "11.1.0"
    steps:
      - checkout

      # Install Xcodegen and create the project file from source
      # Prefix for brew install will cut build times down by 2+ minutes, but
      # could eventually become a problem if Homebrew is out of date.
      - run:
          command: |
            HOMEBREW_NO_AUTO_UPDATE=1 brew install xcodegen
            xcodegen generate

      # Fetch Cocoapods specs from the CircleCI cache to save build time.
      # Sadly, this step still takes ~4 minutes.
      - run:
          name: Fetch CocoaPods specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf

      # Install Cocoapods
      # Caching the Pods directory saves about 30-60 seconds of build time.
      - restore_cache:
          keys: 
            - 1-pods-{{ checksum "Podfile.lock" }}
            - 1-pods-
      - run:
          name: Install Pods
          command: pod install
      - save_cache:
          key: 1-pods-{{ checksum "Podfile.lock" }}
          paths:
            - ./Pods

      # Run Core tests
      - run:
          name: Build and run Core tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: CoreTests

      # Run Rider tests
      - run:
          name: Build and run Rider tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: Rider

      # Run Driver tests
      - run:
          name: Build and run Driver tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 6
            SCAN_SCHEME: Driver
