default_platform(:ios)

platform :ios do

  # Necessary for CircleCI integration
  before_all do
    setup_circle_ci
  end
  
  desc "Build and run all tests"
  lane :test do
    core_tests
    rider_tests
    driver_tests
  end

  desc "Build and run Core tests"
  lane :core_tests do
    run_tests(scheme: "CoreTests")
  end

  desc "Build and run Rider tests"
  lane :rider_tests do
    run_tests(scheme: "Rider")
  end

  desc "Build and run Driver tests"
  lane :driver_tests do
    run_tests(scheme: "Driver")
  end

  desc "Build and deploy all app targets"
  lane :beta do
    increment_build_number(xcodeproj: "Carfie.xcodeproj")
    beta_rider
    beta_driver
  end

  desc "Build and deploy Rider to TestFlight"
  lane :beta_rider do
    build_app(
        scheme: "Rider",
        workspace: "Carfie.xcworkspace",
        include_bitcode: false
    )
    upload_to_testflight()
  end

  desc "Build and deploy Driver to TestFlight"
  lane :beta_driver do
    build_app(
      scheme: "Driver",
      workspace: "Carfie.xcworkspace",
      include_bitcode: false
    )
    upload_to_testflight()
  end
end
